# Generated by Django 3.2.8 on 2021-10-24 19:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('z_awwards', '0002_userpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPost',
            new_name='UserProject',
        ),
    ]
