# Generated by Django 3.2.8 on 2021-10-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_awwards', '0004_projectrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrating',
            name='total_score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
