# Generated by Django 3.2.8 on 2021-10-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_awwards', '0006_auto_20211025_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='Nairobi, KE', max_length=30),
        ),
    ]
