# Generated by Django 3.2.8 on 2021-10-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_awwards', '0007_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
