# Generated by Django 3.2.8 on 2021-10-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_awwards', '0008_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pic/default.png', null=True, upload_to='images/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='photo',
            field=models.ImageField(blank=True, default='images/user_post/default.jpg', upload_to='images/user_post/'),
        ),
    ]
