# Generated by Django 3.2.8 on 2021-10-26 04:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_awwards', '0013_alter_userproject_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dd5ab8mp3/image/upload/v1634659738/profile_pics/default_profile_pic.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dd5ab8mp3/image/upload/v1634659738', max_length=255, verbose_name='image'),
        ),
    ]
