# Generated by Django 3.2.8 on 2021-10-26 05:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_awwards', '0014_auto_20211026_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dd5ab8mp3/image/upload/v1634660213/image/upload/v1/images/profile/user.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dd5ab8mp3/image/upload/v1634660213/image/upload/v1/images/profile/user.jpg', max_length=255, verbose_name='image'),
        ),
    ]
